name: piece-table
version: 0.1.0.0
github: "wasabi315/piece-table"
license: BSD3
author: "Satoshi Takimoto"
maintainer: "wasabi.nvim.st@gmail.com"
copyright: "(c) 2023 Satoshi Takimoto"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: PieceTable implementation in Haskell
category: Text

description: Please see the README on GitHub at <https://github.com/wasabi315/piece-table#readme>

dependencies:
  - base >= 4.7 && < 5
  - fingertree
  - text
  - bytestring

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -O1

library:
  source-dirs: src

executables:
  piece-table:
    main: Main.hs
    source-dirs: app
    dependencies:
      - piece-table

tests:
  piece-table-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - piece-table
      - QuickCheck
